pipeline {
    agent any

    environment {
        IMAGE_NAME = "zavifx/2048-custom-image"
        TAG = "latest"
    }

    stages {
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME:$TAG .'
            }
        }

        stage('Generate Checksum') {
            steps {
                sh './scripts/generate_checksum.sh $IMAGE_NAME $TAG'
            }
        }

        stage('Verify Checksum') {
            steps {
                sh './scripts/verify_checksum.sh $IMAGE_NAME $TAG'
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh '''
                    echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
                    docker push $IMAGE_NAME:$TAG
                    '''
                }
            }
        }
    }

    post {
        failure {
            mail to: 'zavifx@gmail.com',
                 subject: "❌ Jenkins Pipeline Failed",
                 body: "The Jenkins job failed during checksum verification for $IMAGE_NAME:$TAG."
        }
    }
}
