pipeline {
    agent any

    environment {
        IMAGE = "zavifx/2048-custom-image"
        TAG = "latest"
    }

    stages {
        stage('Build Image & Generate Digest') {
            steps {
                sh './scripts/generate_digest.sh'
            }
        }

        stage('Verify Image Digest') {
            steps {
                sh './scripts/verify_digest.sh'
            }
        }

        stage('Deploy Container') {
            steps {
                sh 'docker run -d -p 8080:80 --name game2048 $IMAGE:$TAG'
            }
        }
    }

    post {
        failure {
            echo '❌ Deployment failed due to checksum verification or another issue.'
        }
        success {
            echo '✅ Game 2048 deployed successfully.'
        }
    }
}
